Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [5]:
import numpy as np

In [6]:
input_vector = np.array([1, 2, 3, 4, 5]) 
  
output_matrix_inc = np.vander(input_vector,N=4, increasing = True) 
output_matrix_dec = np.vander(input_vector,N=6, increasing = False)   
print ("The ouput for the increasing boolean argument:")
print(output_matrix_inc)
print ("The ouput for the decreasing boolean argument::")
print(output_matrix_dec)

The ouput for the increasing boolean argument:
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
The ouput for the decreasing boolean argument::
[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]]


Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [7]:
def mov_avg(list_x,k):
    out= []
    i = 0
    z = len(list_x)-k+1
    while i < z:
        b = list_x[i : i + k]
        a = round(sum(b)/ k,2)
        i+=1
        out.append(a)
    return out
list_x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
y=np.array(list_x)
result = mov_avg(y,k)
print("The moving average in an array over a window : " , result)

The moving average in an array over a window :  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
