Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
import numpy as np

In [4]:
input_vector = np.array([1, 2, 3, 4, 5]) 
  
output_matrix_inc = np.vander(input_vector,N=4, increasing = True) 
output_matrix_dec = np.vander(input_vector,N=6, increasing = False)   
print ("The ouput for the increasing boolean argument:")
print(output_matrix_inc)
print ("The ouput for the decreasing boolean argument::")
print(output_matrix_dec)

The ouput for the increasing boolean argument:
[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
The ouput for the decreasing boolean argument::
[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]]


In [3]:
def mov_avg(list_x,k):
    out= []
    i = 0
    z = len(list_x)-k+1
    while i < z:
        b = list_x[i : i + k]
        a = round(sum(b)/ k,2)
        i+=1
        out.append(a)
    return out
list_x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
y=np.array(list_x)
result = mov_avg(y,k)
print("The moving average in an array over a window : " , result)

The moving average in an array over a window :  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
